# @name get-prompts
GET http://localhost:3333/prompts

### 

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/fb633d4c-ca0d-4dd3-98e5-f5784cafe388/transcription
Content-Type: application/json

{
  "prompt": "typescript, programação"
}

###

# @name generate-ai-completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "fb633d4c-ca0d-4dd3-98e5-f5784cafe388",
  "temparature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do video informado a seguir: '''{transcription}'''" 
}
